# Generated by Django 2.1.7 on 2019-03-20 03:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peoples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='موبایل')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'فرد',
                'verbose_name_plural': 'افراد',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Audiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to=settings.AUTH_USER_MODEL, verbose_name='حاضرین')),
            ],
            options={
                'verbose_name': 'حاضرین',
                'verbose_name_plural': 'حاضرین ها',
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='محل')),
                ('Longitude', models.IntegerField(blank=True, null=True, verbose_name='طول جغرافیای محل جلسه')),
                ('Latitude', models.IntegerField(blank=True, null=True, verbose_name='طول جغرافیای محل جلسه')),
                ('_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_owner', to=settings.AUTH_USER_MODEL, verbose_name='برگزارکننده')),
            ],
            options={
                'verbose_name': 'محل',
                'verbose_name_plural': 'محل ها',
            },
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rank', models.CharField(max_length=50, verbose_name='جایگاه')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childern', to='meeting.Ranks', verbose_name='بالا دستی')),
            ],
            options={
                'verbose_name': 'جایگاه',
                'verbose_name_plural': 'جایگاه ها',
                'ordering': ('name_rank',),
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان جلسه')),
                ('start_time', django_jalali.db.models.jDateTimeField(verbose_name='زمان شورع')),
                ('end_time', django_jalali.db.models.jDateTimeField(verbose_name='زمان خاتمه')),
                ('se_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره جلسه')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='برگزارکننده')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place', to='meeting.Places', verbose_name='محل جلسه')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسه ها',
                'ordering': ('start_time',),
            },
        ),
        migrations.AddField(
            model_name='audiences',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='meeting.Sessions', verbose_name='جلسه'),
        ),
        migrations.AddField(
            model_name='peoples',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rank', to='meeting.Ranks', verbose_name='جایگاه'),
        ),
        migrations.AddField(
            model_name='peoples',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
