# Generated by Django 2.1.7 on 2019-03-20 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='_owner',
            new_name='place_owner',
        ),
        migrations.RemoveField(
            model_name='peoples',
            name='rank',
        ),
        migrations.AddField(
            model_name='ranks',
            name='rank_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank_owner', to=settings.AUTH_USER_MODEL, verbose_name='صاحب جایگاه'),
        ),
    ]
