# Generated by Django 2.1.7 on 2019-03-20 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_auto_20190319_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='owner',
        ),
        migrations.AddField(
            model_name='sessions',
            name='meeting_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_owner', to=settings.AUTH_USER_MODEL, verbose_name='برگزارکننده'),
        ),
    ]
