# Generated by Django 2.1.7 on 2019-03-22 22:16

from django.db import migrations, models
import meeting.utils


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_auto_20190320_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoples',
            name='image',
            field=models.ImageField(null=True, upload_to=meeting.utils.get_image_path),
        ),
        migrations.AddField(
            model_name='peoples',
            name='is_legal',
            field=models.BooleanField(default=True, verbose_name='شخصیت حقوقی'),
        ),
    ]
