# Generated by Django 2.1.7 on 2019-03-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_auto_20190322_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoples',
            name='password',
            field=models.CharField(blank=True, default='12345678', max_length=16, null=True, verbose_name='موبایل'),
        ),
    ]
