# Generated by Django 2.1.7 on 2019-03-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0010_auto_20190323_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoples',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
