# Generated by Django 2.1.7 on 2019-03-24 02:18

from django.db import migrations, models
import meeting.utils


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0011_auto_20190323_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoples',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=meeting.utils.get_image_path),
        ),
    ]
