# Generated by Django 2.1.7 on 2019-03-24 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0012_auto_20190323_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranks',
            options={'ordering': ('rank_name',), 'verbose_name': 'جایگاه', 'verbose_name_plural': 'جایگاه ها'},
        ),
        migrations.RenameField(
            model_name='ranks',
            old_name='name_rank',
            new_name='rank_name',
        ),
    ]
