# Generated by Django 2.1.7 on 2019-03-24 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0013_auto_20190323_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='rep_ppl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rep_ppl', to=settings.AUTH_USER_MODEL, verbose_name='جایگزین'),
        ),
    ]
