# Generated by Django 2.1.7 on 2019-04-07 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0014_sessions_rep_ppl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='rep_ppl',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='se_num',
        ),
        migrations.AddField(
            model_name='audiences',
            name='rep_ppl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rep_ppl', to=settings.AUTH_USER_MODEL, verbose_name='جایگزین'),
        ),
    ]
